"""Tests for the sql_generator module."""

import pytest

from app.models import FunctionalConfig, MaskingRule
from app.sql_generator import SQLGenerator


class TestSQLGenerator:
    """Tests for SQLGenerator class."""

    def test_generate_single_rule(self):
        """Test SQL generation for a single masking rule."""
        rules = [
            MaskingRule(
                schema="dbo", table="Personnel", column="LastName", order_by="PersonID"
            )
        ]
        config = FunctionalConfig(
            masking_format="<{column}_{counter}>", pad_length=4, masking_rules=rules
        )

        generator = SQLGenerator()
        sql = generator.generate(config, "MyDb")

        assert "WITH cte AS (" in sql
        assert "ROW_NUMBER() OVER (ORDER BY PersonID)" in sql
        assert "UPDATE cte" in sql
        assert "LastName" in sql
        assert "<LASTNAME_" in sql
        assert "GO" in sql

    def test_generate_multiple_rules(self):
        """Test SQL generation for multiple masking rules."""
        rules = [
            MaskingRule(
                schema="dbo", table="Personnel", column="LastName", order_by="PersonID"
            ),
            MaskingRule(
                schema="dbo", table="Personnel", column="FirstName", order_by="PersonID"
            ),
        ]
        config = FunctionalConfig(
            masking_format="<{column}_{counter}>", pad_length=4, masking_rules=rules
        )

        generator = SQLGenerator()
        sql = generator.generate(config, "MyDb")

        assert sql.count("WITH cte AS") == 2
        assert sql.count("UPDATE cte") == 2
        assert sql.count("GO") == 2
        assert "LastName" in sql
        assert "FirstName" in sql

    def test_generate_pad_length_respected(self):
        """Test that pad_length is correctly applied in generated SQL."""
        rules = [
            MaskingRule(
                schema="dbo", table="Personnel", column="Salary", order_by="PersonID"
            )
        ]
        config = FunctionalConfig(
            masking_format="<{column}_{counter}>", pad_length=6, masking_rules=rules
        )

        generator = SQLGenerator()
        sql = generator.generate(config, "MyDb")

        assert "000000" in sql
        assert "RIGHT('000000' + CAST(rn AS VARCHAR), 6)" in sql

    def test_generate_different_pad_lengths(self):
        """Test SQL generation with different pad_length values."""
        rules_short = [
            MaskingRule(schema="dbo", table="T1", column="C1", order_by="ID")
        ]
        config_short = FunctionalConfig(
            masking_format="<{column}_{counter}>",
            pad_length=2,
            masking_rules=rules_short,
        )

        rules_long = [MaskingRule(schema="dbo", table="T1", column="C1", order_by="ID")]
        config_long = FunctionalConfig(
            masking_format="<{column}_{counter}>",
            pad_length=8,
            masking_rules=rules_long,
        )

        generator = SQLGenerator()
        sql_short = generator.generate(config_short, "MyDb")
        sql_long = generator.generate(config_long, "MyDb")

        assert "RIGHT('00'" in sql_short
        assert "RIGHT('00000000'" in sql_long

    def test_generate_includes_schema_table_column_comments(self):
        """Test that generated SQL includes comments with schema, table, column."""
        rules = [
            MaskingRule(
                schema="MySchema", table="MyTable", column="MyColumn", order_by="ID"
            )
        ]
        config = FunctionalConfig(
            masking_format="<{column}_{counter}>", pad_length=4, masking_rules=rules
        )

        generator = SQLGenerator()
        sql = generator.generate(config, "MyDb")

        assert "-- Database: MyDb" in sql
        assert "-- Schema: MySchema" in sql
        assert "-- Table: MyTable" in sql
        assert "-- Column: MyColumn" in sql
        assert "-- orderBy: ID" in sql
        assert "-- Generated by: Datamasker" in sql
        assert "USE MyDb;" in sql

    def test_generate_no_rules_returns_empty(self):
        """Test that empty rules list returns empty string."""
        config = FunctionalConfig(
            masking_format="<{column}_{counter}>", pad_length=4, masking_rules=[]
        )

        generator = SQLGenerator()
        sql = generator.generate(config, "MyDb")

        assert sql == ""

    def test_generate_column_name_uppercase_in_mask(self):
        """Test that column name is uppercased in the mask value."""
        rules = [
            MaskingRule(
                schema="dbo", table="Personnel", column="lastName", order_by="PersonID"
            )
        ]
        config = FunctionalConfig(
            masking_format="<{column}_{counter}>", pad_length=4, masking_rules=rules
        )

        generator = SQLGenerator()
        sql = generator.generate(config, "MyDb")

        assert "<LASTNAME_" in sql

    def test_generate_correct_masking_format(self):
        """Test the exact masking format in generated SQL."""
        rules = [
            MaskingRule(schema="dbo", table="Employee", column="SSN", order_by="EmpID")
        ]
        config = FunctionalConfig(
            masking_format="<{column}_{counter}>", pad_length=4, masking_rules=rules
        )

        generator = SQLGenerator()
        sql = generator.generate(config, "MyDb")

        assert "<SSN_" in sql
        assert "RIGHT('0000' + CAST(rn AS VARCHAR), 4)" in sql
        assert "SET SSN = '<SSN_' + " in sql

    def test_generate_with_different_order_by(self):
        """Test SQL generation with different orderBy columns."""
        rules = [
            MaskingRule(
                schema="dbo", table="Orders", column="OrderDate", order_by="OrderID"
            ),
            MaskingRule(
                schema="dbo", table="Orders", column="ShipDate", order_by="OrderID"
            ),
        ]
        config = FunctionalConfig(
            masking_format="<{column}_{counter}>", pad_length=5, masking_rules=rules
        )

        generator = SQLGenerator()
        sql = generator.generate(config, "MyDb")

        assert sql.count("ROW_NUMBER() OVER (ORDER BY OrderID)") == 2
        assert "OrderDate" in sql
        assert "ShipDate" in sql

    def test_generate_preserves_order_by_column_in_update(self):
        """Test that orderBy column is used in ROW_NUMBER but not in UPDATE SET."""
        rules = [
            MaskingRule(
                schema="dbo", table="Personnel", column="FirstName", order_by="PersonID"
            )
        ]
        config = FunctionalConfig(
            masking_format="<{column}_{counter}>", pad_length=4, masking_rules=rules
        )

        generator = SQLGenerator()
        sql = generator.generate(config, "MyDb")

        assert "ROW_NUMBER() OVER (ORDER BY PersonID)" in sql
        assert "SET FirstName" in sql
        assert "PersonID = " not in sql.split("SET FirstName")[1].split(";")[0]

    def test_generate_sql_ends_with_go(self):
        """Test that generated SQL blocks end with GO statement."""
        rules = [MaskingRule(schema="dbo", table="T", column="C", order_by="ID")]
        config = FunctionalConfig(
            masking_format="<{column}_{counter}>", pad_length=4, masking_rules=rules
        )

        generator = SQLGenerator()
        sql = generator.generate(config, "MyDb")

        assert sql.strip().endswith("GO")

    def test_generate_sql_block_separation(self):
        """Test that multiple SQL blocks are properly separated."""
        rules = [
            MaskingRule(schema="dbo", table="T1", column="C1", order_by="ID"),
            MaskingRule(schema="dbo", table="T2", column="C2", order_by="ID"),
        ]
        config = FunctionalConfig(
            masking_format="<{column}_{counter}>", pad_length=4, masking_rules=rules
        )

        generator = SQLGenerator()
        sql = generator.generate(config, "MyDb")

        assert "\n\n" in sql
        blocks = sql.split("\n\n")
        assert len(blocks) == 2
        for block in blocks:
            assert "WITH cte AS" in block
            assert "UPDATE cte" in block
            assert "GO" in block
