"""SQL masking script generator."""

from typing import List

from app.models import FunctionalConfig, MaskingRule


class SQLGenerator:
    """Generates SQL Server data masking scripts from validated configuration."""

    def generate(self, config: FunctionalConfig) -> str:
        """Generate a complete SQL masking script.

        Args:
            config: The validated functional configuration.

        Returns:
            A string containing the complete SQL script.

        Raises:
            SQLGenerationError: If generation fails.
        """
        if not config.masking_rules:
            return ""

        sql_blocks: List[str] = []

        for rule in config.masking_rules:
            block = self._generate_block(rule, config.masking_format, config.pad_length)
            sql_blocks.append(block)

        return "\n\n".join(sql_blocks) + "\n"

    def _generate_block(
        self, rule: MaskingRule, masking_format: str, pad_length: int
    ) -> str:
        """Generate a SQL block for a single masking rule.

        Args:
            rule: The masking rule to generate SQL for.
            masking_format: The masking format template string.
            pad_length: The zero-padding length for the counter.

        Returns:
            A formatted SQL block as a string.
        """
        padded_counter = "'" + "0" * pad_length + "'"
        cast_rn = "CAST(rn AS VARCHAR)"
        right_padding = "RIGHT({}, LEN({}))".format(padded_counter, padded_counter)

        pad_expr = (
            "RIGHT('"
            + "0" * pad_length
            + "' + "
            + cast_rn
            + ", "
            + str(pad_length)
            + ")"
        )

        column_upper = rule.column.upper()
        mask_value = "'<" + column_upper + "_' + " + pad_expr + " + '>'"

        sql = """-- ===============================================
-- MASKING RULE
-- Schema: {schema}
-- Table: {table}
-- Column: {column}
-- orderBy: {order_by}
-- Generated by: Datamasker
-- ===============================================
WITH cte AS (
    SELECT {order_by}, ROW_NUMBER() OVER (ORDER BY {order_by}) AS rn
    FROM {schema}.{table}
)
UPDATE cte
SET {column} = {mask_value};
GO""".format(
            schema=rule.schema,
            table=rule.table,
            column=rule.column,
            order_by=rule.order_by,
            mask_value=mask_value,
        )

        return sql
