#Requires -Version 5.1
<#
.SYNOPSIS
    PowerShell wrapper for Datamasker SQL Server data masking script generator.

.DESCRIPTION
    This script orchestrates the Datamasker Python CLI to perform SQL Server data
    masking operations including DPAPI password encryption, connection testing,
    SQL script generation, and optional script execution via sqlcmd.

    The script supports the following actions:
    - EncryptPassword: Encrypt a SQL Server password using DPAPI
    - TestConnection: Validate SQL Server connectivity
    - GenerateSql: Generate masking.sql from configuration files
    - ExecuteSql: Execute masking.sql through sqlcmd
    - FullRun: Perform the complete end-to-end workflow

    For automation and scheduling, use the -NoConfirm switch to skip interactive
    confirmations and -DryRun to validate without executing sqlcmd.

.PARAMETER Action
    The operation to perform. Valid values are: EncryptPassword, TestConnection,
    GenerateSql, ExecuteSql, FullRun. This parameter is required.

.PARAMETER Config
    Path to the functional masking configuration JSON file. Required for
    GenerateSql and FullRun actions.

.PARAMETER Connection
    Path to the technical connection configuration JSON file. Required for
    TestConnection, GenerateSql, and FullRun actions.

.PARAMETER SqlFile
    Path for the generated SQL masking script. Defaults to .\masking.sql.
    Used by GenerateSql and FullRun to determine output location, and by
    ExecuteSql to determine which file to execute.

.PARAMETER ProjectRoot
    Root directory of the Datamasker project. Defaults to the directory
    containing this script's parent directory (i.e., the repository root).
    Used to locate the virtualenv and configuration files.

.PARAMETER PythonExe
    Path to the Python executable within the virtualenv. Defaults to
    .\.venv\Scripts\python.exe relative to ProjectRoot.

.PARAMETER NoConfirm
    Suppresses interactive confirmation prompts. Use this switch for
    automation, scripting, and scheduled tasks. If not specified,
    ExecuteSql and FullRun will prompt for confirmation before executing SQL.

.PARAMETER DryRun
    Validates all inputs and generates the SQL script but skips actual
    sqlcmd execution. Use this to verify the workflow without making
    database changes. Applicable to ExecuteSql and FullRun actions.

.PARAMETER LogFile
    Optional path to a log file. If specified, operational messages are
    written to this file in addition to the console.

.EXAMPLE
    Encrypt a SQL Server password:
    .\scripts\datamasker.ps1 -Action EncryptPassword

.EXAMPLE
    Test SQL Server connection:
    .\scripts\datamasker.ps1 -Action TestConnection -Connection ".\sample.connection.json"

.EXAMPLE
    Generate the masking SQL script:
    .\scripts\datamasker.ps1 -Action GenerateSql -Config ".\sample.masking.json" -Connection ".\sample.connection.json"

.EXAMPLE
    Generate SQL and execute it (with confirmation):
    .\scripts\datamasker.ps1 -Action FullRun -Config ".\sample.masking.json" -Connection ".\sample.connection.json"

.EXAMPLE
    Execute an existing masking.sql (with confirmation):
    .\scripts\datamasker.ps1 -Action ExecuteSql -Connection ".\sample.connection.json" -SqlFile ".\masking.sql"

.EXAMPLE
    Full run without prompts (for automation):
    .\scripts\datamasker.ps1 -Action FullRun -Config ".\sample.masking.json" -Connection ".\sample.connection.json" -NoConfirm

.EXAMPLE
    Dry run to validate everything without executing SQL:
    .\scripts\datamasker.ps1 -Action FullRun -Config ".\sample.masking.json" -Connection ".\sample.connection.json" -DryRun

.EXAMPLE
    Windows Task Scheduler usage:
    powershell.exe -ExecutionPolicy Bypass -File "C:\tools\datamasker\scripts\datamasker.ps1" -Action FullRun -Config "C:\tools\datamasker\sample.masking.json" -Connection "C:\tools\datamasker\sample.connection.json" -SqlFile "C:\tools\datamasker\masking.sql" -NoConfirm

.NOTES
    File Name: datamasker.ps1
    Author:   Jerome COLLETTE
    Version:  1.0.0

    SECURITY NOTES:

    - DPAPI decryption depends on the Windows account context. The encrypted password
      file must have been generated by the same Windows user account that runs this
      script. If the scheduled task runs under a specific service account, generate
      the DPAPI file using that same account.

    - sqlcmd credential handling: This script does not pass passwords to sqlcmd
      on the command line. Use SQL Server authentication with -U/-P prompts, or
      prefer Windows Authentication (-E) when available. Using -P MyPassword on
      the command line exposes the password in process listings, logs, and shell
      history.

    - Never commit unencrypted passwords or DPAPI files to version control.
      The secrets/ directory should be protected with NTFS permissions.

    EXIT CODES:
    0   Success
    1   Error (validation, configuration, or execution failure)
    2   Invalid parameter combination
#>

[CmdletBinding()]
param(
    [Parameter(HelpMessage = "Action to perform: EncryptPassword, TestConnection, GenerateSql, ExecuteSql, FullRun")]
    [ValidateSet("EncryptPassword", "TestConnection", "GenerateSql", "ExecuteSql", "FullRun")]
    [string]$Action = $null,

    [Parameter(HelpMessage = "Path to functional masking configuration JSON file")]
    [string]$Config,

    [Parameter(HelpMessage = "Path to technical connection configuration JSON file")]
    [string]$Connection,

    [Parameter(HelpMessage = "Path for generated SQL masking script (default: .\masking.sql)")]
    [string]$SqlFile = $null,

    [Parameter(HelpMessage = "Datamasker project root directory (default: script parent directory)")]
    [string]$ProjectRoot = $null,

    [Parameter(HelpMessage = "Python executable path (default: .\.venv\Scripts\python.exe relative to ProjectRoot)")]
    [string]$PythonExe = $null,

    [Parameter(HelpMessage = "Suppress confirmation prompts for automation")]
    [switch]$NoConfirm = $false,

    [Parameter(HelpMessage = "Validate but skip actual SQL execution")]
    [switch]$DryRun = $false,

    [Parameter(HelpMessage = "Optional log file path")]
    [string]$LogFile = $null
)

#region User Configuration Section
$DefaultAction = ""           # EncryptPassword, TestConnection, GenerateSql, ExecuteSql, FullRun
$DefaultConfig = ""           # Path to functional masking configuration JSON file
$DefaultConnection = ""       # Path to technical connection configuration JSON file
$DefaultSqlFile = ""          # Path for generated SQL masking script
$DefaultProjectRoot = ""      # Root directory of Datamasker project (default: script parent dir)
$DefaultPythonExe = ""        # Python executable path
$DefaultNoConfirm = $false    # Suppress confirmation prompts
$DefaultDryRun = $false       # Validate but skip SQL execution
$DefaultLogFile = ""          # Optional log file path
#endregion

$ErrorActionPreference = "Stop"
Set-StrictMode -Version 5.1

if (-not $Action) { $Action = $DefaultAction }
if (-not $Config) { $Config = $DefaultConfig }
if (-not $Connection) { $Connection = $DefaultConnection }
if (-not $SqlFile) { $SqlFile = if ($DefaultSqlFile) { $DefaultSqlFile } else { ".\masking.sql" } }
if (-not $ProjectRoot) { $ProjectRoot = $DefaultProjectRoot }
if (-not $PythonExe) { $PythonExe = $DefaultPythonExe }
if (-not $NoConfirm) { $NoConfirm = $DefaultNoConfirm }
if (-not $DryRun) { $DryRun = $DefaultDryRun }
if (-not $LogFile) { $LogFile = $DefaultLogFile }

function Write-LogMessage {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Message,

        [Parameter(Mandatory = $false)]
        [ValidateSet("INFO", "WARN", "ERROR", "SUCCESS")]
        [string]$Level = "INFO"
    )

    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logEntry = "[$timestamp] [$Level] $Message"

    switch ($Level) {
        "ERROR" { Write-Host $logEntry -ForegroundColor Red }
        "WARN"  { Write-Host $logEntry -ForegroundColor Yellow }
        "SUCCESS" { Write-Host $logEntry -ForegroundColor Green }
        default { Write-Host $logEntry }
    }

    if ($LogFile) {
        try {
            Add-Content -Path $LogFile -Value $logEntry -ErrorAction SilentlyContinue
        }
        catch {
            Write-Host "WARNING: Could not write to log file: $LogFile" -ForegroundColor Yellow
        }
    }
}

function Resolve-ProjectPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,

        [Parameter(Mandatory = $true)]
        [string]$BasePath
    )

    if ([System.IO.Path]::IsPathRooted($Path)) {
        return $Path
    }

    return Join-Path -Path $BasePath -ChildPath $Path
}

function Test-FileExists {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,

        [Parameter(Mandatory = $true)]
        [string]$Description
    )

    if (-not (Test-Path -Path $Path -PathType Leaf)) {
        Write-LogMessage -Message "$Description not found: $Path" -Level ERROR
        return $false
    }

    return $true
}

function Invoke-PythonCli {
    param(
        [Parameter(Mandatory = $true)]
        [string]$PythonExe,

        [Parameter(Mandatory = $true)]
        [string[]]$Arguments,

        [Parameter(Mandatory = $false)]
        [string]$Description
    )

    Write-LogMessage -Message "Executing: $PythonExe $($Arguments -join ' ')" -Level INFO

    if ($Description) {
        Write-LogMessage -Message $Description -Level INFO
    }

    try {
        $process = Start-Process -FilePath $PythonExe -ArgumentList $Arguments -NoNewWindow -Wait -PassThru -RedirectStandardOutput stdout.txt -RedirectStandardError stderr.txt

        $stdout = Get-Content -Path ".\stdout.txt" -Raw -ErrorAction SilentlyContinue
        $stderr = Get-Content -Path ".\stderr.txt" -Raw -ErrorAction SilentlyContinue

        Remove-Item -Path ".\stdout.txt" -ErrorAction SilentlyContinue
        Remove-Item -Path ".\stderr.txt" -ErrorAction SilentlyContinue

        if ($stdout) {
            $stdout.Trim() -split "`n" | ForEach-Object { Write-LogMessage -Message $_.Trim() -Level SUCCESS }
        }

        if ($stderr) {
            $stderr.Trim() -split "`n" | ForEach-Object { Write-LogMessage -Message $_.Trim() -Level ERROR }
        }

        if ($process.ExitCode -ne 0) {
            Write-LogMessage -Message "Python CLI exited with code: $($process.ExitCode)" -Level ERROR
            return $false
        }

        return $true
    }
    catch {
        Write-LogMessage -Message "Failed to execute Python CLI: $_" -Level ERROR
        return $false
    }
}

function Invoke-EncryptPassword {
    param(
        [Parameter(Mandatory = $true)]
        [string]$PythonExe
    )

    Write-LogMessage -Message "Starting DPAPI password encryption" -Level INFO
    Write-LogMessage -Message "The Python CLI will prompt for the SQL Server password" -Level INFO

    $args = @("-m", "app.cli", "encrypt-password", "--output", "secrets\sql-password.dpapi")

    $result = Invoke-PythonCli -PythonExe $PythonExe -Arguments $args -Description "Prompting for SQL Server password..."

    if ($result) {
        Write-LogMessage -Message "DPAPI password file created successfully" -Level SUCCESS
        Write-LogMessage -Message "Encrypted file: secrets\sql-password.dpapi" -Level INFO
        return $true
    }

    Write-LogMessage -Message "DPAPI password encryption failed" -Level ERROR
    return $false
}

function Invoke-TestConnection {
    param(
        [Parameter(Mandatory = $true)]
        [string]$PythonExe,

        [Parameter(Mandatory = $true)]
        [string]$ConnectionPath
    )

    Write-LogMessage -Message "Testing SQL Server connection" -Level INFO
    Write-LogMessage -Message "Connection file: $ConnectionPath" -Level INFO

    if (-not (Test-FileExists -Path $ConnectionPath -Description "Connection file")) {
        return $false
    }

    $connectionConfig = Get-Content -Path $ConnectionPath -Raw | ConvertFrom-Json -ErrorAction SilentlyContinue
    if ($connectionConfig -and $connectionConfig.passwordFile) {
        $passwordFilePath = Resolve-ProjectPath -Path $connectionConfig.passwordFile -BasePath (Split-Path -Parent $ConnectionPath)
        if (-not (Test-FileExists -Path $passwordFilePath -Description "DPAPI password file")) {
            Write-LogMessage -Message "DPAPI password file referenced in connection config not found: $passwordFilePath" -Level ERROR
            return $false
        }
        Write-LogMessage -Message "DPAPI password file found: $passwordFilePath" -Level INFO
    }

    $args = @("-m", "app.cli", "test-connection", "--connection", $ConnectionPath)

    $result = Invoke-PythonCli -PythonExe $PythonExe -Arguments $args

    if ($result) {
        Write-LogMessage -Message "Connection test completed successfully" -Level SUCCESS
        return $true
    }

    Write-LogMessage -Message "Connection test failed" -Level ERROR
    return $false
}

function Invoke-GenerateSql {
    param(
        [Parameter(Mandatory = $true)]
        [string]$PythonExe,

        [Parameter(Mandatory = $true)]
        [string]$ConfigPath,

        [Parameter(Mandatory = $true)]
        [string]$ConnectionPath,

        [Parameter(Mandatory = $true)]
        [string]$SqlFilePath
    )

    Write-LogMessage -Message "Generating masking SQL script" -Level INFO
    Write-LogMessage -Message "Config file: $ConfigPath" -Level INFO
    Write-LogMessage -Message "Connection file: $ConnectionPath" -Level INFO
    Write-LogMessage -Message "Output file: $SqlFilePath" -Level INFO

    if (-not (Test-FileExists -Path $ConfigPath -Description "Config file")) {
        return $false
    }

    if (-not (Test-FileExists -Path $ConnectionPath -Description "Connection file")) {
        return $false
    }

    $args = @("-m", "app.cli", "generate", "--config", $ConfigPath, "--connection", $ConnectionPath, "--output", $SqlFilePath)

    $result = Invoke-PythonCli -PythonExe $PythonExe -Arguments $args

    if ($result) {
        Write-LogMessage -Message "Masking SQL script generated successfully" -Level SUCCESS
        Write-LogMessage -Message "Script file: $SqlFilePath" -Level INFO
        return $true
    }

    Write-LogMessage -Message "SQL script generation failed" -Level ERROR
    return $false
}

function Invoke-ExecuteSql {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ConnectionPath,

        [Parameter(Mandatory = $true)]
        [string]$SqlFilePath,

        [Parameter(Mandatory = $false)]
        [switch]$NoConfirm,

        [Parameter(Mandatory = $false)]
        [switch]$DryRun
    )

    Write-LogMessage -Message "Executing masking SQL script via sqlcmd" -Level INFO
    Write-LogMessage -Message "SQL file: $SqlFilePath" -Level INFO

    if (-not (Test-FileExists -Path $SqlFilePath -Description "SQL file")) {
        return $false
    }

    if (-not (Test-FileExists -Path $ConnectionPath -Description "Connection file")) {
        return $false
    }

    $connectionConfig = Get-Content -Path $ConnectionPath -Raw | ConvertFrom-Json -ErrorAction SilentlyContinue
    if (-not $connectionConfig) {
        Write-LogMessage -Message "Failed to parse connection file: $ConnectionPath" -Level ERROR
        return $false
    }

    $server = $connectionConfig.server
    $database = $connectionConfig.database
    $username = $connectionConfig.username

    if (-not $server -or -not $database) {
        Write-LogMessage -Message "Connection file must specify 'server' and 'database'" -Level ERROR
        return $false
    }

    if ($DryRun) {
        Write-LogMessage -Message "DRY RUN MODE: Validating SQL file but skipping execution" -Level WARN
        Write-LogMessage -Message "Would execute: sqlcmd -S $server -d $database -U $username -i `"$SqlFilePath`"" -Level INFO
        Write-LogMessage -Message "Dry run completed successfully" -Level SUCCESS
        return $true
    }

    if (-not $NoConfirm) {
        Write-LogMessage -Message "WARNING: About to execute SQL UPDATE statements on database '$database' on server '$server'" -Level WARN
        Write-LogMessage -Message "The masking script will modify data in the database" -Level WARN

        $confirm = Read-Host -Prompt "Do you want to continue? (yes/no)"
        if ($confirm -ne "yes") {
            Write-LogMessage -Message "Operation cancelled by user" -Level WARN
            return $false
        }
    }

    Write-LogMessage -Message "Executing sqlcmd. SQL authentication will be prompted." -Level INFO
    Write-LogMessage -Message "If you prefer Windows Authentication, use -E flag manually with sqlcmd" -Level INFO

    try {
        $sqlCmdArgs = @("-S", $server, "-d", $database, "-U", $username, "-i", $SqlFilePath)

        $process = Start-Process -FilePath "sqlcmd" -ArgumentList $sqlCmdArgs -NoNewWindow -Wait -PassThru

        if ($process.ExitCode -eq 0) {
            Write-LogMessage -Message "SQL script executed successfully" -Level SUCCESS
            return $true
        }
        else {
            Write-LogMessage -Message "sqlcmd exited with code: $($process.ExitCode)" -Level ERROR
            return $false
        }
    }
    catch {
        Write-LogMessage -Message "Failed to execute sqlcmd: $_" -Level ERROR
        Write-LogMessage -Message "Make sure sqlcmd is installed and available in PATH" -Level ERROR
        return $false
    }
}

function Invoke-FullRun {
    param(
        [Parameter(Mandatory = $true)]
        [string]$PythonExe,

        [Parameter(Mandatory = $true)]
        [string]$ConfigPath,

        [Parameter(Mandatory = $true)]
        [string]$ConnectionPath,

        [Parameter(Mandatory = $true)]
        [string]$SqlFilePath,

        [Parameter(Mandatory = $false)]
        [switch]$NoConfirm,

        [Parameter(Mandatory = $false)]
        [switch]$DryRun
    )

    Write-LogMessage -Message "===============================================" -Level INFO
    Write-LogMessage -Message "Starting FullRun: Complete masking workflow" -Level INFO
    Write-LogMessage -Message "===============================================" -Level INFO

    Write-LogMessage -Message "Step 1/4: Validating environment" -Level INFO

    if (-not (Test-FileExists -Path $ConfigPath -Description "Config file")) {
        return $false
    }

    if (-not (Test-FileExists -Path $ConnectionPath -Description "Connection file")) {
        return $false
    }

    Write-LogMessage -Message "Step 2/4: Testing SQL Server connection" -Level INFO

    if (-not (Invoke-TestConnection -PythonExe $PythonExe -ConnectionPath $ConnectionPath)) {
        Write-LogMessage -Message "FullRun aborted: Connection test failed" -Level ERROR
        return $false
    }

    Write-LogMessage -Message "Step 3/4: Generating masking SQL script" -Level INFO

    if (-not (Invoke-GenerateSql -PythonExe $PythonExe -ConfigPath $ConfigPath -ConnectionPath $ConnectionPath -SqlFilePath $SqlFilePath)) {
        Write-LogMessage -Message "FullRun aborted: SQL generation failed" -Level ERROR
        return $false
    }

    Write-LogMessage -Message "Step 4/4: Executing masking SQL script" -Level INFO

    if (-not (Invoke-ExecuteSql -ConnectionPath $ConnectionPath -SqlFilePath $SqlFilePath -NoConfirm:$NoConfirm -DryRun:$DryRun)) {
        Write-LogMessage -Message "FullRun aborted: SQL execution failed" -Level ERROR
        return $false
    }

    Write-LogMessage -Message "===============================================" -Level INFO
    Write-LogMessage -Message "FullRun completed successfully" -Level SUCCESS
    Write-LogMessage -Message "===============================================" -Level INFO

    return $true
}

function Main {
    $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

    if (-not $ProjectRoot) {
        $ProjectRoot = Split-Path -Parent $scriptDir
    }

    if (-not $PythonExe) {
        $PythonExe = Join-Path -Path $ProjectRoot -ChildPath ".venv\Scripts\python.exe"
    }

    Write-LogMessage -Message "Datamasker PowerShell Wrapper" -Level INFO
    Write-LogMessage -Message "Action: $Action" -Level INFO
    Write-LogMessage -Message "ProjectRoot: $ProjectRoot" -Level INFO
    Write-LogMessage -Message "PythonExe: $PythonExe" -Level INFO

    if (-not (Test-Path -Path $PythonExe -PathType Leaf)) {
        Write-LogMessage -Message "Python executable not found: $PythonExe" -Level ERROR
        Write-LogMessage -Message "Ensure the virtualenv is created and PythonExe path is correct" -Level ERROR
        exit 1
    }

    if (-not $NoConfirm -and -not $DryRun -and $Action -ne "EncryptPassword" -and $Action -ne "TestConnection" -and $Action -ne "GenerateSql") {
        Write-LogMessage -Message "WARNING: This action will execute SQL statements against the database" -Level WARN
        $confirm = Read-Host -Prompt "Do you want to continue? (yes/no)"
        if ($confirm -ne "yes") {
            Write-LogMessage -Message "Operation cancelled by user" -Level WARN
            exit 0
        }
    }

    $resolvedConfig = $null
    $resolvedConnection = $null
    $resolvedSqlFile = $null

    if ($Config) {
        $resolvedConfig = Resolve-ProjectPath -Path $Config -BasePath $ProjectRoot
    }

    if ($Connection) {
        $resolvedConnection = Resolve-ProjectPath -Path $Connection -BasePath $ProjectRoot
    }

    if ($SqlFile) {
        $resolvedSqlFile = Resolve-ProjectPath -Path $SqlFile -BasePath $ProjectRoot
    }

    $success = $false

    switch ($Action) {
        "EncryptPassword" {
            $success = Invoke-EncryptPassword -PythonExe $PythonExe
        }

        "TestConnection" {
            if (-not $resolvedConnection) {
                Write-LogMessage -Message "Connection parameter is required for TestConnection action" -Level ERROR
                exit 2
            }
            $success = Invoke-TestConnection -PythonExe $PythonExe -ConnectionPath $resolvedConnection
        }

        "GenerateSql" {
            if (-not $resolvedConfig) {
                Write-LogMessage -Message "Config parameter is required for GenerateSql action" -Level ERROR
                exit 2
            }
            if (-not $resolvedConnection) {
                Write-LogMessage -Message "Connection parameter is required for GenerateSql action" -Level ERROR
                exit 2
            }
            $success = Invoke-GenerateSql -PythonExe $PythonExe -ConfigPath $resolvedConfig -ConnectionPath $resolvedConnection -SqlFilePath $resolvedSqlFile
        }

        "ExecuteSql" {
            if (-not $resolvedConnection) {
                Write-LogMessage -Message "Connection parameter is required for ExecuteSql action" -Level ERROR
                exit 2
            }
            if (-not $resolvedSqlFile) {
                Write-LogMessage -Message "SqlFile parameter is required for ExecuteSql action" -Level ERROR
                exit 2
            }
            $success = Invoke-ExecuteSql -ConnectionPath $resolvedConnection -SqlFilePath $resolvedSqlFile -NoConfirm:$NoConfirm -DryRun:$DryRun
        }

        "FullRun" {
            if (-not $resolvedConfig) {
                Write-LogMessage -Message "Config parameter is required for FullRun action" -Level ERROR
                exit 2
            }
            if (-not $resolvedConnection) {
                Write-LogMessage -Message "Connection parameter is required for FullRun action" -Level ERROR
                exit 2
            }
            $success = Invoke-FullRun -PythonExe $PythonExe -ConfigPath $resolvedConfig -ConnectionPath $resolvedConnection -SqlFilePath $resolvedSqlFile -NoConfirm:$NoConfirm -DryRun:$DryRun
        }
    }

    if ($success) {
        Write-LogMessage -Message "Operation completed successfully" -Level SUCCESS
        exit 0
    }
    else {
        Write-LogMessage -Message "Operation failed" -Level ERROR
        exit 1
    }
}

Main
